name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          config_padding: 0, -10%
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_introduction: yes
          plugin_introduction_title: no
          plugin_traffic: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 2465955
          plugin_stackoverflow_sections: ""
          plugin_stars: yes
          plugin_stars_limit: 2

      - uses: lowlighter/metrics@latest
        with:
          filename: followers.svg
          config_padding: 0, -10%
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: followers

      - uses: lowlighter/metrics@latest
        with:
          filename: xkcd.svg
          config_padding: 0, -10%
          token: NOT_NEEDED
          base: ""
          plugin_screenshot: yes
          plugin_screenshot_title: XKCD of the day
          plugin_screenshot_url: https://xkcd.com
          plugin_screenshot_selector: "#comic img"
