name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    permissions:
      contents: write
    steps:
      # ref: https://github.com/lowlighter/metrics#-documentation
      #
      # Your GitHub token
      # The following scopes are required:
      #  - public_access (default scope)
      # The following additional scopes may be required:
      #  - read:org      (for organization related metrics)
      #  - read:user     (for user related data)
      #  - read:packages (for some packages related data)
      #  - repo          (optional, if you want to include private repositories)
      #
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: BirkhoffLee
          template: classic
          base: header, activity, community, repositories
          base_indepth: yes
          config_timezone: Europe/Rome
          repositories_forks: yes
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 2465955
          plugin_stackoverflow_sections: ""
          plugin_stars: yes
          plugin_stars_limit: 2

      - uses: lowlighter/metrics@latest
        with:
          filename: followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 48
