name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: head, repositories
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 2465955
          plugin_stackoverflow_sections: ""
          plugin_stars: yes
          plugin_stars_limit: 2

      - uses: lowlighter/metrics@latest
        with:
          filename: followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: followers
          plugin_people_limit: 48
